#include "LLMUtil/VerificationAgent.h"
#include "CCPG/CCPGNode.h"
#include "CPG/Node.h"
#include "CCPG/ThreadCreationTree.h"
#include "CCPG/CCPG.h"
#include "LLMUtil/SharedToolKit.h"
#include "LLMUtil/ThreadPair.h"
#include <sstream>
#include <iostream>
#include <queue>
#include <set>

namespace llm_client {

// Helper function to sanitize strings for valid UTF-8
static std::string sanitize_utf8(const std::string& input) {
    std::string output;
    output.reserve(input.size());
    for (unsigned char c : input) {
        // Replace non-ASCII and control characters (except newline/tab) with '?'
        if (c < 0x20 && c != '\n' && c != '\t' && c != '\r') {
            output += '?';
        } else if (c >= 0x80) {
            // For simplicity, replace all high bytes - can be made smarter for actual UTF-8
            output += '?';
        } else {
            output += static_cast<char>(c);
        }
    }
    return output;
}

VerificationAgent::VerificationAgent(std::shared_ptr<LLMClient> client)
    : Conversation(client, "", 20), 
      ccpg_(ThreadCreationTree::getInstance()->getCCPG()) {
      
    set_system_prompt(buildVerificationSystemPrompt());
}

bool VerificationAgent::verifyBug(const query::StatefulBug& bug) {
    reset();
    current_bug_ = &bug;
    has_verdict_ = false;
    verdict_ = false;

    std::string prompt = buildBugReportPrompt(bug);
    std::cout << "    [VerificationAgent] Starting interactive verification..." << std::endl;
    
    // We pass `this` as context for tools
    send_message(prompt, (void*)this);

    if (has_verdict_) {
        std::cout << "    [VerificationAgent] Verdict Reached: " << (verdict_ ? "TRUE POSITIVE" : "FALSE POSITIVE") << std::endl;
        return verdict_;
    } else {
        std::cout << "    [VerificationAgent] No clear verdict reached. Defaulting to FALSE POSITIVE (Conservative)." << std::endl;
        return false;
    }
}

std::string VerificationAgent::buildVerificationSystemPrompt() {
    return R"(You are a senior C/C++ concurrency security researcher.
I will provide you with a "Suspected Bug Report" generated by a static analysis tool.
This report includes a "Violation Path" - a sequence of operations (e.g., READ, WRITE, FREE) across threads that allegedly leads to a vulnerability.

**Your Task:**
Verify if this is a REAL bug (True Positive) or a False Positive.
Static analysis often misses context like:
1.  **Guards**: Is the access protected by a mutex, check, or flag?
2.  **Reachability**: Are the paths actually executable?
3.  **Benign Patterns**: Is this a known benign race?
4.  **Concurrency**: Can these threads actually run concurrently in a way that triggers the bug?

**Your Capability:**
You CANNOT see the full codebase initially. You MUST use the provided tools to "investigate" the crime scene.
Do not guess. Explore the code using the tools.

**Process:**
1.  **Inspect the Path**: Use `get_violation_path_context` first to see the code around the reported violation points.
2.  **Trace Back**: Use `get_call_chain_to_node` to understand how the thread reached these points. This helps in checking reachability conditions.
3.  **Check Details**: Use `get_function_code` to see full function bodies for local guards (locks, if-checks). Use `get_variable_definition` to understand variable types.
4.  **Verdict**: Once you have gathered enough evidence, submit your verdict.
)";
}

std::string VerificationAgent::buildBugReportPrompt(const query::StatefulBug& bug) {
    std::stringstream ss;
    const auto& rule = bug.getRule();
    const auto& threads = bug.getThreadPair();

    ss << "## Suspected Bug Report\n\n";
    ss << "**Bug Type:** " << (rule.contains("pattern_type") ? rule["pattern_type"].get<std::string>() : "Unknown") << "\n";
    ss << "**Description:** " << (rule.contains("_llm_summary") ? rule["_llm_summary"].get<std::string>() : "No description") << "\n\n";

    ss << "**Analysis Context:**\n";
    ss << "- Designed for Parallelism: " << (threads.analysis.designed_for_parallelism ? "YES" : "NO") << "\n";
    if (threads.analysis.designed_for_parallelism) {
        ss << "  Reasoning: " << threads.analysis.design_reasoning << "\n";
    }
    ss << "- Actually Concurrent: " << (threads.analysis.actually_concurrent ? "YES" : "NO") << "\n";
    if (threads.analysis.actually_concurrent) {
        ss << "  Reasoning: " << threads.analysis.concurrency_reasoning << "\n";
    }

    ss << "\n**Concurrency Contract (Thread 1 - ID " << threads.thread1->getId() << "):**\n";
    ss << "- Role: " << threads.contract1.role << "\n";
    ss << "- Sync Strategy: " << threads.contract1.synchronization.strategy << "\n";
    if (!threads.contract1.synchronization.primitives.empty()) {
        ss << "- Primitives: ";
        for (const auto& prim : threads.contract1.synchronization.primitives) ss << prim.identifier << ", ";
        ss << "\n";
    }

    ss << "\n**Concurrency Contract (Thread 2 - ID " << threads.thread2->getId() << "):**\n";
    ss << "- Role: " << threads.contract2.role << "\n";
    ss << "- Sync Strategy: " << threads.contract2.synchronization.strategy << "\n";
    if (!threads.contract2.synchronization.primitives.empty()) {
        ss << "- Primitives: ";
        for (const auto& prim : threads.contract2.synchronization.primitives) ss << prim.identifier << ", ";
        ss << "\n";
    }

    ss << "\nThe Violation Path contains " << bug.getPath().size() << " critical steps.\n";
    ss << "Please use `get_violation_path_context` to examine them in detail.\n";
    
    return ss.str();
}

std::vector<Tool> VerificationAgent::get_available_tools() const {
    auto tools = SharedToolKit::get_shared_tools(); // Include basic tools like get_function

    tools.push_back({
        "get_violation_path_context", 
        "Retrieves the detailed code context for each step in the reported violation path.", 
        {}
    });

    tools.push_back({
        "get_call_chain_to_node", 
        "Retrieves the call stack (chain of functions) from the thread entry point down to the function containing the specified node.", 
        {
            {"node_id", "number", "The ID of the node in the violation path.", true}
        }
    });

    tools.push_back({
        "get_function_code", 
        "Retrieves the full source code of a function.", 
        {
            {"function_id", "number", "The ID of the function.", true}
        }
    });
    
    tools.push_back({
        "get_variable_definition",
        "Attempts to find the definition of a variable used at a specific location.",
        {
            {"variable_name", "string", "The name of the variable.", true},
            {"node_id", "number", "The ID of the node where the variable is used.", true}
        }
    });

    tools.push_back({
        "submit_verdict", 
        "Submits the final verification verdict.", 
        {
            {"verdict", "string", "Must be 'TRUE_POSITIVE' or 'FALSE_POSITIVE'.", true},
            {"confidence", "string", "High, Medium, or Low.", true},
            {"reasoning", "string", "Explanation for the verdict.", true}
        }
    });

    return tools;
}

std::string VerificationAgent::execute_tool(const std::string& tool_name, const nlohmann::json& arguments) {
    // Try shared tools first
    auto shared_result = SharedToolKit::handle_shared_tool(tool_name, arguments, ccpg_);
    if (shared_result) { return *shared_result; }

    if (tool_name == "get_violation_path_context") {
        if (!current_bug_) return R"({"error": "No active bug report."})";

        nlohmann::json path_info = nlohmann::json::array();
        for (const auto& step : current_bug_->getPath()) {
            std::string role = step.first;
            CCPGNode* node = step.second;

            if (!node || !node->getCPGNode()) continue;

            nlohmann::json step_info;
            step_info["role"] = role;
            step_info["node_id"] = node->getId();
            step_info["location"] = node->getNodeLoc().toString();
            
            // Get function info
            ccpg::Function* func = node->getFunction();
            if (func) {
                step_info["function_id"] = func->getId();
                step_info["function_name"] = func->getFuncNode()->getCPGNode()->getName();
                
                // Get full code with marker (sanitize for valid UTF-8)
                std::string full_code = sanitize_utf8(func->getFuncNode()->getCPGNode()->getCode());
                std::string line_code = sanitize_utf8(node->getCPGNode()->getCode());
                
                // Simple string replacement to highlight (this is a heuristic)
                size_t pos = full_code.find(line_code);
                if (pos != std::string::npos) {
                    full_code.insert(pos, " /* <<< VIOLATION POINT */ ");
                }
                step_info["function_code_snippet"] = full_code; 
            } else {
                 step_info["function_name"] = "Unknown";
                 step_info["code_snippet"] = sanitize_utf8(node->getCPGNode()->getCode());
            }
            
            path_info.push_back(step_info);
        }
        return path_info.dump();
    }

    if (tool_name == "get_call_chain_to_node") {
        int target_node_id = arguments.at("node_id").get<int>();
        CCPGNode* target_node = ccpg_->getNodeByID(target_node_id);
        if (!target_node) return R"({"error": "Node not found."})";

        ccpg::Function* target_func = target_node->getFunction();
        if (!target_func) return R"({"error": "Node does not belong to a valid function."})";

        // Simple BFS/DFS on Call Graph from Thread Entry
        // Since we don't store the exact call stack in the node, we search for *a* path from Thread Entry to this function.
        // We need to know which thread this node belongs to.
        
        Thread* relevant_thread = nullptr;
        if (current_bug_) {
            const auto& pair = current_bug_->getThreadPair();
            if (pair.thread1->getNodes().count(target_node)) relevant_thread = pair.thread1;
            else if (pair.thread2->getNodes().count(target_node)) relevant_thread = pair.thread2;
        }

        if (!relevant_thread) return R"({"error": "Could not determine thread for this node."})";
        
        ccpg::Function* entry_func = relevant_thread->getThreadMainFunction();
        if (!entry_func) return R"({"error": "Thread has no entry function."})";
        
        if (entry_func == target_func) {
             return R"({"status": "Node is in the thread entry function."})";
        }

        // BFS to find path from entry_func to target_func in the Call Graph
        std::queue<std::pair<ccpg::Function*, std::vector<std::string>>> q;
        std::set<ccpg::Function*> visited;
        
        q.push({entry_func, {entry_func->getFuncNode()->getCPGNode()->getName()}});
        visited.insert(entry_func);

        while(!q.empty()) {
            auto [curr_func, path] = q.front();
            q.pop();

            if (curr_func == target_func) {
                nlohmann::json result;
                result["call_chain"] = path;
                return result.dump();
            }
            
            // Get callees
            for (CCPGNode* node : curr_func->getNodes()) {
                if (node->isCallSite()) {
                    CCPGEdge* callEdge = ccpg_->hasCallEdge(node);
                    if (callEdge) {
                        CCPGNode* calleeNode = callEdge->getDst();
                        if (calleeNode) {
                            ccpg::Function* callee = calleeNode->getFunction();
                            if (callee && visited.find(callee) == visited.end()) {
                                visited.insert(callee);
                                std::vector<std::string> new_path = path;
                                new_path.push_back(callee->getFuncNode()->getCPGNode()->getName());
                                q.push({callee, new_path});
                            }
                        }
                    }
                }
            }
        }
        
        return R"({"status": "No static call path found from thread entry to this function (could be due to function pointers or incomplete CG)."})";
    }

    if (tool_name == "get_function_code") {
        // SharedToolkit already has get_function_by_id, but it returns JSON. 
        // We can just reuse handle_shared_tool logic or reimplement for cleaner output if needed.
        return *SharedToolKit::handle_shared_tool("get_function_by_id", arguments, ccpg_);
    }
    
    if (tool_name == "get_variable_definition") {
        // This is complex to implement robustly without def-use chains.
        // For now, return a placeholder or simple search.
        return R"({"status": "Tool not fully implemented yet. Please inspect function code manually."})";
    }

    if (tool_name == "submit_verdict") {
        std::string verdict_str = arguments.at("verdict").get<std::string>();
        verdict_ = (verdict_str == "TRUE_POSITIVE");
        has_verdict_ = true;
        return "Verdict recorded. Analysis session ending.";
    }

    return R"({"error": "Tool not found."})";
}

} // namespace llm_client
