#ifndef CONCURRENCYCONTRACT_H
#define CONCURRENCYCONTRACT_H

#include <string>
#include <vector>
#include <map>
#include <cstdint>
#include <optional>
#include "nlohmann/json.hpp"

namespace LLM {

// Using a clear type alias for NodeID within the CCPG
using NodeID = uint64_t;

/**
 * @class ConcurrencyContract
 * @brief A contract describing the concurrent behavior of a single thread.
 *
 * This class is generated by an Architect Agent, reviewed by a Critic Agent,
 * and used by an Auditor Agent to generate verification queries against the CCPG.
 * It is the bridge between LLM semantic understanding and static graph analysis.
 */
class ConcurrencyContract {
public:
    // ========================================================================
    // 1. Core Identity
    // ========================================================================

    NodeID threadEntryPointFunctionID;
    std::string threadName;

    enum class ThreadRole {
        UNKNOWN,
        WORKER,
        LISTENER,
        PERIODIC_TASK,
        IO_BOUND,
        CPU_BOUND
    };
    ThreadRole role;

    // ========================================================================
    // 2. Core Shared State
    // ========================================================================

    struct SharedResource {
        NodeID cpgNodeID;
        std::string variableName;
        std::string typeName;
    };

    std::vector<SharedResource> coreSharedState;

    // ========================================================================
    // 3. Synchronization Discipline
    // ========================================================================

    struct LockIdentifier {
        NodeID cpgNodeID;
        std::string lockName;
        bool isCustom = false;
    };

    struct DataLockBinding {
        LockIdentifier lock;
        std::vector<SharedResource> protectedResources;
    };

    struct LockOrderConstraint {
        std::vector<LockIdentifier> orderedLocks;
    };

    struct CustomSyncProtocol {
        LockIdentifier primitiveIdentifier;
        NodeID lockFunctionID;
        NodeID unlockFunctionID;
    };
    
    struct Synchronization {
        std::vector<DataLockBinding> dataLockBindings;
        std::vector<LockOrderConstraint> lockOrders;
        std::vector<CustomSyncProtocol> customProtocols;
    };

    Synchronization syncDiscipline;

    // ========================================================================
    // 4. Behavioral Properties
    // ========================================================================

    struct StateMachineModel {
        SharedResource stateVariable;
        std::string initialState;
        struct Transition {
            std::string fromState;
            std::string toState;
            NodeID triggerActionNodeID;
        };
        std::vector<Transition> transitions;
    };

    struct HappensBeforeConstraint {
        NodeID sourceActionNodeID;
        NodeID sinkActionNodeID;
        std::string logicDescription;
    };
    
    std::optional<StateMachineModel> stateModel;
    std::vector<HappensBeforeConstraint> happensBeforeConstraints;

    // ========================================================================
    // 5. Metadata
    // ========================================================================

    double confidenceScore;
    std::string reasoning;
    std::vector<std::string> criticFeedback;
    int version;

public:
    ConcurrencyContract(NodeID entryPoint);

    std::string toJson() const;
    static ConcurrencyContract fromJson(const std::string& jsonString);
};

// Comparison operator for LockIdentifier to be used in std::map
bool operator<(const ConcurrencyContract::LockIdentifier& lhs, const ConcurrencyContract::LockIdentifier& rhs);

} // namespace LLM

#endif // CONCURRENCYCONTRACT_H