#!/bin/bash
set -o pipefail

LLM4CON_HOME="${LLM4CON_HOME:-/home/LLM4Con}"
KERNEL_DIR="${LINUX_REPO:-${KERNEL_DIR:-/home/ConCord/targets/linux.git}}"
EXPERIMENT_BASE="${EXPERIMENT_BASE:-${LLM4CON_HOME}/kernel_experiment}"
REPORTS_DIR="${REPORTS_DIR:-/home/ConCord/concurrency_cve_reports/linux_kernel}"
CLANG=${CLANG:-clang}
SURVEY_FILE="${SURVEY_FILE:-/tmp/cve_survey.csv}"
NJOBS=${NJOBS:-$(nproc)}
FORCE=${FORCE:-0}
LOGFILE="${EXPERIMENT_BASE}/batch_prepare.log"

SUCCESS=0
FAIL=0
SKIP=0
FAIL_LIST=""
LAST_PREPARED_COMMIT=""
TOTAL_PATCH=0
CURRENT=0

# Phase F (M7): patch-driven file expansion (set EXPAND_PATCH=0 to disable).
# patch_expander reads via `git show $commit:path` so it works without
# touching the worktree, hence safe for our batched checkout flow.
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
EXPAND_PATCH=${EXPAND_PATCH:-1}
EXPANDED=0
EXPAND_FAIL=0

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOGFILE"; }

checkout_and_prepare() {
    local commit="$1"

    if [ "$LAST_PREPARED_COMMIT" = "$commit" ]; then
        log "    reusing prepared tree for ${commit:0:12}"
        return 0
    fi

    cd "$KERNEL_DIR" || return 1
    rm -f .git/index.lock

    log "    checkout ${commit:0:12}~1 ..."
    if ! git checkout --force --quiet "${commit}~1" 2>/dev/null; then
        if ! git checkout --force --quiet "${commit}^" 2>/dev/null; then
            return 1
        fi
    fi

    log "    cleaning generated dirs..."
    git clean -fdxq -- include/generated/ include/config/ \
        arch/x86/include/generated/ scripts/ 2>/dev/null || true

    log "    make allyesconfig..."
    if ! make allyesconfig CC=gcc HOSTCC=gcc >/dev/null 2>&1; then
        log "    allyesconfig failed, trying defconfig..."
        make defconfig CC=gcc HOSTCC=gcc >/dev/null 2>&1 || true
    fi

    log "    make modules_prepare (j$NJOBS)..."
    # KCFLAGS appends to kernel's own CFLAGS (preserving -fcf-protection=branch
    # required by v6.x IBT __nocf_check attributes); -fno-PIE/-fno-pic works
    # around Debian 12 GCC 12 hardened defaults vs -mcmodel=kernel.
    local kprep_kcflags="-fno-PIE -fno-pic"
    make modules_prepare CC=gcc HOSTCC=gcc KCFLAGS="$kprep_kcflags" -j"$NJOBS" >/dev/null 2>&1 || \
    make prepare         CC=gcc HOSTCC=gcc KCFLAGS="$kprep_kcflags" -j"$NJOBS" >/dev/null 2>&1 || true

    # When `make prepare` fails (old kernels, missing tools, etc.) install
    # the same minimal shims as prepare_cve.sh so single-TU clang compilation
    # can proceed instead of bailing out.
    local gen_dir="$KERNEL_DIR/include/generated"
    mkdir -p "$gen_dir"
    if [ ! -f "$gen_dir/bounds.h" ]; then
        cat > "$gen_dir/bounds.h" <<'BOUNDS_EOF'
/* Auto-generated shim - batch_prepare.sh fallback.
 * Values mirror an allyesconfig x86_64 build's generated bounds.h so that
 * single-TU clang compiles get sensible BITS_PER_LONG-scale constants. */
#ifndef __LINUX_BOUNDS_H__
#define __LINUX_BOUNDS_H__
#define NR_PAGEFLAGS 22
#define MAX_NR_ZONES 4
#define NR_CPUS_BITS 13          /* log2(CONFIG_NR_CPUS=8192) */
#define SPINLOCK_SIZE 4
#define MAX_LOCKDEP_SUBCLASSES 8
#define MAX_LOCKDEP_KEYS_BITS 14
#define LAST_CPUPID_SHIFT 0
#endif
BOUNDS_EOF
        log "    installed fallback include/generated/bounds.h"
    fi
    if [ ! -f "$gen_dir/autoconf.h" ]; then
        cat > "$gen_dir/autoconf.h" <<'AUTOCONF_EOF'
/* Auto-generated shim - batch_prepare.sh fallback */
#ifndef __LINUX_AUTOCONF_H__
#define __LINUX_AUTOCONF_H__
#define CONFIG_64BIT 1
#define CONFIG_X86_64 1
#define CONFIG_SMP 1
#define CONFIG_PRINTK 1
#define CONFIG_BUG 1
#define CONFIG_BASE_SMALL 0
#define CONFIG_LOG_BUF_SHIFT 17
#endif
AUTOCONF_EOF
        log "    installed fallback include/generated/autoconf.h"
    fi
    [ -f "$gen_dir/utsrelease.h" ] || echo '#define UTS_RELEASE "shim"' > "$gen_dir/utsrelease.h"
    [ -f "$gen_dir/timeconst.h" ]  || echo '/* shim */' > "$gen_dir/timeconst.h"

    # Wrapper that wins against <linux/module.h>'s own re-definition of
    # module_init / *_initcall. Without this, `-D` on the clang command line
    # is silently overridden by the kernel header, causing duplicate
    # __inittest / init_module symbols when a TU contains both module_init
    # and (e.g.) late_initcall (post-v5.x kernels alias late_initcall to
    # module_init under -DMODULE).
    cat > "$gen_dir/lace_initcall_override.h" <<'OVR_EOF'
/* Auto-generated by batch_prepare.sh — pre-include module.h, then redefine
 * its initcall aliases so each TU gets a uniquely-named marker function
 * instead of duplicate __inittest / init_module emissions. */
#ifndef _LACE_INITCALL_OVERRIDE_H
#define _LACE_INITCALL_OVERRIDE_H
#include <linux/module.h>
#undef module_init
#define module_init(fn) \
    static inline int __mi_##fn(void) __attribute__((used,unused)); \
    static inline int __mi_##fn(void) { return (fn)(); }
#undef module_exit
#define module_exit(fn) \
    static inline void __mx_##fn(void) __attribute__((used,unused)); \
    static inline void __mx_##fn(void) { (fn)(); }
#undef early_initcall
#define early_initcall(fn) module_init(fn)
#undef core_initcall
#define core_initcall(fn) module_init(fn)
#undef core_initcall_sync
#define core_initcall_sync(fn) module_init(fn)
#undef postcore_initcall
#define postcore_initcall(fn) module_init(fn)
#undef postcore_initcall_sync
#define postcore_initcall_sync(fn) module_init(fn)
#undef arch_initcall
#define arch_initcall(fn) module_init(fn)
#undef subsys_initcall
#define subsys_initcall(fn) module_init(fn)
#undef subsys_initcall_sync
#define subsys_initcall_sync(fn) module_init(fn)
#undef fs_initcall
#define fs_initcall(fn) module_init(fn)
#undef fs_initcall_sync
#define fs_initcall_sync(fn) module_init(fn)
#undef rootfs_initcall
#define rootfs_initcall(fn) module_init(fn)
#undef device_initcall
#define device_initcall(fn) module_init(fn)
#undef device_initcall_sync
#define device_initcall_sync(fn) module_init(fn)
#undef late_initcall
#define late_initcall(fn) module_init(fn)
#undef late_initcall_sync
#define late_initcall_sync(fn) module_init(fn)
#undef console_initcall
#define console_initcall(fn) module_init(fn)
#endif /* _LACE_INITCALL_OVERRIDE_H */
OVR_EOF

    if [ ! -f arch/x86/include/generated/asm/asm-offsets.h ] && \
       [ ! -f include/generated/asm-offsets.h ]; then
        log "    asm-offsets.h missing, trying manual build..."
        make arch/x86/kernel/asm-offsets.s CC=gcc HOSTCC=gcc 2>/dev/null || true
    fi
    # If asm-offsets.h is still missing after a manual attempt, write an
    # empty placeholder so the `arch/x86/include/asm/asm-offsets.h` wrapper
    # (which just does `#include <generated/asm-offsets.h>`) doesn't blow
    # up. Files that actually reference offsets at compile time will fail
    # later; files that only transitively #include this header still
    # build. Same fallback pattern as bounds.h above.
    if [ ! -f include/generated/asm-offsets.h ] && \
       [ ! -f arch/x86/include/generated/asm/asm-offsets.h ]; then
        echo '/* batch_prepare.sh fallback - empty asm-offsets shim */' \
            > "$gen_dir/asm-offsets.h"
        log "    installed empty include/generated/asm-offsets.h shim"
    fi

    LAST_PREPARED_COMMIT="$commit"
    return 0
}

build_compile_cmd() {
    local src_file="$1" out_ll="$2"
    local base
    base=$(basename "$src_file" .c)
    local src_dir
    src_dir=$(dirname "$src_file")

    local sysinclude
    sysinclude=$($CLANG -print-file-name=include 2>/dev/null)

    local inc="-nostdinc -isystem $sysinclude"
    inc="$inc -I$KERNEL_DIR/include -I$KERNEL_DIR/include/uapi"
    inc="$inc -I$KERNEL_DIR/arch/x86/include -I$KERNEL_DIR/arch/x86/include/uapi"
    inc="$inc -I$KERNEL_DIR/arch/x86/include/generated -I$KERNEL_DIR/arch/x86/include/generated/uapi"
    [ -d "$KERNEL_DIR/include/generated" ] && inc="$inc -I$KERNEL_DIR/include/generated"
    [ -d "$KERNEL_DIR/include/generated/uapi" ] && inc="$inc -I$KERNEL_DIR/include/generated/uapi"
    [ -d "$KERNEL_DIR/$src_dir" ] && inc="$inc -I$KERNEL_DIR/$src_dir"

    # also add parent dirs for local includes (e.g. drivers/gpu/drm/amd/amdkfd -> amdgpu)
    local parent_dir=$(dirname "$src_dir")
    if [ "$parent_dir" != "$src_dir" ] && [ -d "$KERNEL_DIR/$parent_dir" ]; then
        for sub in "$KERNEL_DIR/$parent_dir"/*/; do
            [ -d "$sub" ] && inc="$inc -I$sub"
        done
    fi

    # Subsystem-specific cross-tree quoted-includes. Same dispatch table as
    # prepare_cve.sh — purely build-system workarounds driven by path layout,
    # so they cannot bias detection results.
    case "$src_file" in
        drivers/gpu/drm/amd/*)
            while IFS= read -r d; do
                inc="$inc -I$d"
            done < <(find "$KERNEL_DIR/drivers/gpu/drm/amd" -type d 2>/dev/null)
            for sub in include drm; do
                [ -d "$KERNEL_DIR/include/$sub" ] && inc="$inc -I$KERNEL_DIR/include/$sub"
            done
            inc="$inc -DCONFIG_DEBUG_FS=1 -DCONFIG_DRM_AMD_DC=1"
            ;;
        drivers/crypto/chelsio/chtls/*|drivers/net/ethernet/chelsio/inline_crypto/chtls/*)
            # chtls drivers include "t4fw_api.h" from the sibling cxgb4 dir.
            for sub in drivers/net/ethernet/chelsio/cxgb4 \
                       drivers/net/ethernet/chelsio/inline_crypto \
                       drivers/crypto/chelsio; do
                [ -d "$KERNEL_DIR/$sub" ] && inc="$inc -I$KERNEL_DIR/$sub"
            done
            ;;
        drivers/gpu/drm/nouveau/*)
            for sub in drivers/gpu/drm/nouveau/include \
                       drivers/gpu/drm/nouveau/include/nvkm \
                       drivers/gpu/drm/nouveau/include/nvif \
                       drivers/gpu/drm/nouveau/nvkm/include \
                       drivers/gpu/drm/nouveau \
                       drivers/gpu/drm/nouveau/nvkm; do
                [ -d "$KERNEL_DIR/$sub" ] && inc="$inc -I$KERNEL_DIR/$sub"
            done
            ;;
    esac

    local forced=""
    [ -f "$KERNEL_DIR/include/linux/compiler-version.h" ] && \
        forced="$forced -include $KERNEL_DIR/include/linux/compiler-version.h"
    forced="$forced -include $KERNEL_DIR/include/generated/autoconf.h"
    [ -f "$KERNEL_DIR/include/linux/kconfig.h" ] && \
        forced="$forced -include $KERNEL_DIR/include/linux/kconfig.h"
    [ -f "$KERNEL_DIR/include/linux/compiler_types.h" ] && \
        forced="$forced -include $KERNEL_DIR/include/linux/compiler_types.h"
    # Pre-include the initcall override so subsequent re-includes of
    # <linux/module.h> hit its header guard and our redefined initcall
    # aliases win. See lace_initcall_override.h installation above.
    [ -f "$KERNEL_DIR/include/generated/lace_initcall_override.h" ] && \
        forced="$forced -include $KERNEL_DIR/include/generated/lace_initcall_override.h"

    local defs="-D__KERNEL__ -DMODULE"
    defs="$defs -DKBUILD_MODNAME=\\\"${base}\\\""
    defs="$defs -DKBUILD_BASENAME=\\\"${base}\\\""
    defs="$defs -DCONFIG_SMP -DCONFIG_64BIT -DCONFIG_X86_64"
    defs="$defs -DCONFIG_SPARSEMEM -DCONFIG_X86_L1_CACHE_SHIFT=6"
    defs="$defs -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1"
    defs="$defs -DCONFIG_CC_HAS_ASM_GOTO_OUTPUT=1 -DCONFIG_FUNCTION_ALIGNMENT=16"
    defs="$defs -DCC_USING_FENTRY"
    defs="$defs -DCONFIG_FTRACE_MCOUNT_USE_OBJTOOL=1"
    defs="$defs '-D__copy(x)='"
    defs="$defs '-D__compiletime_object_size(x)=-1'"
    defs="$defs '-D__compiletime_warning(x)='"
    defs="$defs '-D__compiletime_error(x)='"
    defs="$defs '-Dearly_param(name,fn)='"
    defs="$defs -mfentry"

    # Neutralise initcall expansions so multiple inclusions of <linux/module.h>
    # don't produce duplicate init_module / __inittest symbols at single-TU
    # compile time. Mirrors prepare_cve.sh NEUTER_INITCALL.
    defs="$defs '-Dmodule_init(fn)=static int __mi_##fn(void) __attribute__((used,unused));static int __mi_##fn(void){return (fn)();}'"
    defs="$defs '-Dearly_initcall(fn)=static int __ei_##fn(void) __attribute__((used,unused));static int __ei_##fn(void){return (fn)();}'"
    defs="$defs '-Dcore_initcall(fn)=static int __ci_##fn(void) __attribute__((used,unused));static int __ci_##fn(void){return (fn)();}'"
    defs="$defs '-Dpostcore_initcall(fn)=static int __pci_##fn(void) __attribute__((used,unused));static int __pci_##fn(void){return (fn)();}'"
    defs="$defs '-Darch_initcall(fn)=static int __ai_##fn(void) __attribute__((used,unused));static int __ai_##fn(void){return (fn)();}'"
    defs="$defs '-Dsubsys_initcall(fn)=static int __si_##fn(void) __attribute__((used,unused));static int __si_##fn(void){return (fn)();}'"
    defs="$defs '-Dfs_initcall(fn)=static int __fi_##fn(void) __attribute__((used,unused));static int __fi_##fn(void){return (fn)();}'"
    defs="$defs '-Ddevice_initcall(fn)=static int __di_##fn(void) __attribute__((used,unused));static int __di_##fn(void){return (fn)();}'"
    defs="$defs '-Dlate_initcall(fn)=static int __li_##fn(void) __attribute__((used,unused));static int __li_##fn(void){return (fn)();}'"
    defs="$defs '-Dmodule_exit(fn)=static void __mx_##fn(void) __attribute__((used,unused));static void __mx_##fn(void){(fn)();}'"

    echo "$CLANG -S -emit-llvm -g -O0 -Wno-everything -fno-pic -fno-PIE \
        -target x86_64-linux-gnu $defs $inc $forced \
        $KERNEL_DIR/$src_file -o $out_ll"
}

do_compile() {
    local cve="$1" commit="$2" files_str="$3"
    local exp_dir="$EXPERIMENT_BASE/$cve"

    if [ "$FORCE" != "1" ] && ls "$exp_dir"/*.ll >/dev/null 2>&1; then
        SKIP=$((SKIP+1))
        return 0
    fi

    IFS=';' read -ra USER_SRC_FILES <<< "$files_str"
    local SRC_FILES=("${USER_SRC_FILES[@]}")

    if [ "$EXPAND_PATCH" = "1" ] && [ -x "$SCRIPT_DIR/patch_expander.py" ]; then
        local seed_args=()
        for f in "${USER_SRC_FILES[@]}"; do
            f=$(echo "$f" | xargs)
            [ -n "$f" ] && seed_args+=("$f")
        done
        local exp_dir_pre="$EXPERIMENT_BASE/$cve"
        mkdir -p "$exp_dir_pre"
        local _expansion_log="$exp_dir_pre/expansion.log"
        mapfile -t EXPANDED_FILES < <(
            "$SCRIPT_DIR/patch_expander.py" \
                --kernel-dir "$KERNEL_DIR" \
                --commit "$commit" \
                --seeds "${seed_args[@]}" \
                --output "$exp_dir_pre" 2>"$_expansion_log"
        )
        if [ ${#EXPANDED_FILES[@]} -gt 0 ]; then
            local seed_count=${#seed_args[@]}
            local final_count=${#EXPANDED_FILES[@]}
            if [ "$final_count" -gt "$seed_count" ]; then
                log "    patch expansion: $seed_count -> $final_count files"
                EXPANDED=$((EXPANDED + 1))
            fi
            SRC_FILES=("${EXPANDED_FILES[@]}")
        else
            EXPAND_FAIL=$((EXPAND_FAIL + 1))
        fi
    fi

    local c_files=() seen=()
    for f in "${SRC_FILES[@]}"; do
        f=$(echo "$f" | xargs)
        [ -z "$f" ] && continue
        [[ "$f" != *.c ]] && continue
        local dup=0; for s in "${seen[@]}"; do [ "$s" = "$f" ] && dup=1; done
        [ "$dup" = "1" ] && continue
        c_files+=("$f"); seen+=("$f")
    done
    if [ ${#c_files[@]} -eq 0 ]; then
        SKIP=$((SKIP+1))
        return 0
    fi

    CURRENT=$((CURRENT + 1))
    log "[$CURRENT/$TOTAL_PATCH] $cve — ${#c_files[@]} files"

    if ! checkout_and_prepare "$commit"; then
        log "  FAIL (checkout/prepare)"
        FAIL=$((FAIL + 1)); FAIL_LIST="$FAIL_LIST $cve(checkout)"
        return 1
    fi

    for f in "${c_files[@]}"; do
        if [ ! -f "$KERNEL_DIR/$f" ]; then
            log "  FAIL (missing $f)"
            FAIL=$((FAIL + 1)); FAIL_LIST="$FAIL_LIST $cve(missing)"
            return 1
        fi
    done

    mkdir -p "$exp_dir/src"
    for f in "${SRC_FILES[@]}"; do
        f=$(echo "$f" | xargs); [ -z "$f" ] && continue
        if [ -f "$KERNEL_DIR/$f" ]; then
            mkdir -p "$exp_dir/src/$(dirname "$f")"
            cp "$KERNEL_DIR/$f" "$exp_dir/src/$(dirname "$f")/" 2>/dev/null || true
        fi
    done
    for f in "${c_files[@]}"; do
        local dir=$(dirname "$f")
        mkdir -p "$exp_dir/src/$dir"
        for hdr in "$KERNEL_DIR/$dir"/*.h; do
            [ -f "$hdr" ] || continue
            cp -n "$hdr" "$exp_dir/src/$dir/" 2>/dev/null || true
        done
    done

    local bc_files=() fail_files=()
    for f in "${c_files[@]}"; do
        local base=$(basename "$f" .c)
        local bcfile="$exp_dir/${base}.ll"
        local logf="$exp_dir/${base}_compile.log"
        local cmd=$(build_compile_cmd "$f" "$bcfile")
        printf '### compile cmd:\n%s\n### end cmd\n' "$cmd" > "$logf"
        if eval $cmd 2>>"$logf"; then
            bc_files+=("$bcfile")
            log "    ${base}.ll OK"
        else
            fail_files+=("$f")
            log "    ${base}.ll FAIL"
        fi
    done

    if [ ${#bc_files[@]} -gt 1 ]; then
        # Rename per-TU @init_module / @cleanup_module so llvm-link doesn't
        # bail on duplicate symbols (each kernel TU's <linux/module.h> emits
        # its own copy as a module-local alias). Same trick as prepare_cve.sh.
        for bc in "${bc_files[@]}"; do
            local stem=$(basename "$bc" .ll | tr -c 'A-Za-z0-9_' _)
            sed -i -E \
                -e "s/@init_module([^A-Za-z0-9_])/@init_module_${stem}\\1/g" \
                -e "s/@cleanup_module([^A-Za-z0-9_])/@cleanup_module_${stem}\\1/g" \
                "$bc"
        done
        if llvm-link -S "${bc_files[@]}" -o "$exp_dir/merged.ll" \
                2>"$exp_dir/llvm-link.log"; then
            log "    merged.ll OK ($(wc -l < "$exp_dir/merged.ll") lines)"
        else
            log "    merged.ll FAIL (see llvm-link.log)"
        fi
    fi

    if [ ${#bc_files[@]} -eq 0 ]; then
        log "  RESULT: FAIL (0/${#c_files[@]} compiled)"
        FAIL=$((FAIL + 1)); FAIL_LIST="$FAIL_LIST $cve(compile)"
        return 1
    fi

    if [ ${#fail_files[@]} -gt 0 ]; then
        log "  RESULT: PARTIAL (${#bc_files[@]}/${#c_files[@]})"
    else
        log "  RESULT: OK (${#bc_files[@]} .ll)"
    fi
    SUCCESS=$((SUCCESS + 1))
}

collect_ground_truth() {
    local cve="$1" commit="$2" files_str="$3"
    local exp_dir="$EXPERIMENT_BASE/$cve"
    local gt_file="$exp_dir/ground_truth.json"
    [ -d "$exp_dir" ] || return 0
    ls "$exp_dir"/*.ll >/dev/null 2>&1 || return 0
    [ -f "$gt_file" ] && [ "$FORCE" != "1" ] && return 0

    python3 - "$cve" "$commit" "$files_str" "$REPORTS_DIR" "$gt_file" << 'PYEOF'
import json, os, sys
cve_id, commit, files_str, reports_dir, gt_file = sys.argv[1:6]
gt = {"cve_id": cve_id, "files": [f.strip() for f in files_str.split(";") if f.strip()], "fix_commit": commit}
metadata_file = os.path.join(reports_dir, cve_id, "metadata.json")
if os.path.exists(metadata_file):
    with open(metadata_file) as f:
        meta = json.load(f)
    for d in meta.get("cve", {}).get("descriptions", []):
        if d.get("lang") == "en":
            gt["description"] = d["value"]; break
    cwes = []
    for w in meta.get("cve", {}).get("weaknesses", []):
        for dd in w.get("description", []):
            if dd.get("value", "").startswith("CWE"): cwes.append(dd["value"])
    gt["cwes"] = cwes
for fname, key, maxlen in [("summary.md","summary",2000),("analysis.md","analysis",3000)]:
    fpath = os.path.join(reports_dir, cve_id, fname)
    if os.path.exists(fpath):
        with open(fpath) as f: gt[key] = f.read()[:maxlen]
patch_file = os.path.join(reports_dir, cve_id, "patch.diff")
if os.path.exists(patch_file):
    with open(patch_file) as f: gt["patch"] = f.read()[:5000]
pctx_file = os.path.join(reports_dir, cve_id, "patch_context.json")
if os.path.exists(pctx_file):
    with open(pctx_file) as f: pctx = json.load(f)
    af = []
    for sec in pctx.get("sections",[]):
        for fi in sec.get("files",[]): p=fi.get("path",""); p and af.append(p)
    if af: gt["affected_files_from_patch"] = list(dict.fromkeys(af))
with open(gt_file, "w") as f: json.dump(gt, f, indent=2, ensure_ascii=False)
PYEOF
}

# --- main ---
mkdir -p "$EXPERIMENT_BASE"
echo "" > "$LOGFILE"

TOTAL_PATCH=$(tail -n +2 "$SURVEY_FILE" | awk -F, '$2=="YES" && $4!=""' | wc -l)

log "============================================"
log " Batch CVE Preparation"
log " Survey: $SURVEY_FILE ($TOTAL_PATCH CVEs with patch)"
log " Kernel: $KERNEL_DIR"
log " Output: $EXPERIMENT_BASE"
log "============================================"

# 按年份降序处理（优先新的 CVE）
while IFS=, read -r cve has_patch files commit; do
    [ "$cve" = "CVE" ] && continue
    [ "$has_patch" != "YES" ] && continue
    [ -z "$commit" ] && continue
    commit=$(echo "$commit" | tr -d '[:space:]')
    do_compile "$cve" "$commit" "$files" || true
done < <(tail -n +2 "$SURVEY_FILE" | sort -t'-' -k2,2nr -k3,3nr | sed '1i CVE,HAS_PATCH,FILES,FIX_COMMIT' | tail -n +2)

log ""
log "--- Collecting Ground Truth ---"
while IFS=, read -r cve has_patch files commit; do
    [ "$cve" = "CVE" ] && continue
    [ "$has_patch" != "YES" ] && continue
    [ -z "$commit" ] && continue
    commit=$(echo "$commit" | tr -d '[:space:]')
    collect_ground_truth "$cve" "$commit" "$files"
done < "$SURVEY_FILE"

log ""
log "============================================"
log " DONE: $SUCCESS OK, $FAIL failed, $SKIP skipped"
log " Patch expansion: $EXPANDED CVEs expanded, $EXPAND_FAIL failed (set EXPAND_PATCH=0 to disable)"
[ -n "$FAIL_LIST" ] && log " Failed:$FAIL_LIST"
log "============================================"
